# Generated by Django 2.1.7 on 2019-05-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpractice', '0002_auto_20190510_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='body',
        ),
    ]
