# Generated by Django 2.1.7 on 2019-05-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpractice', '0003_auto_20190511_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
